name: Py38
channels:
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.32
  - hdf5=1.12.1
  - ipykernel=6.15.2
  - ipywidget
  - jupyter=1.0.0
  - lmfit=1.0.3
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.4.3
  - phconvert=0.9
  - pybroom=0.2
  - pytables=3.7.0
  - python=3.8.13
  - scipy=1.7.3
  - seaborn=0.11.2
  - terminado=0.13.1
  - tornado=6.2
  - fretbursts=0.7.1
